spring:
  application:
    name: fake-flex

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %-5level [%thread] [corrId=%X{correlationId}] %logger{36} - %msg%n"
