spring:
  application:
    name: fake-flex

  config:
    import: "optional:file:./config/dev-application.yml"

server:
  port: ${FLEX_SERVER_PORT}
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: ${SHUTDOWN_TIMEOUT:30s}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info}

logging:
  pattern:
    console: ${LOG_PATTERN}

